version: '3'

services:
  postgresql:
    image: postgres
    container_name: DB-box
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pas123
      - POSTGRES_DATABASE=base
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379-6379'
